Models/BaseViewModel.cs
namespace TrabajoFinal___Bingo_Web_MVC_Service.Models
{
    public class BaseViewModel
    {
        public int Id { get; set; }
    }
}

Models/BingoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TrabajoFinal___Bingo_Web_MVC_Service.Models
{
    public class BingoViewModel : BaseViewModel
    {
        public int PlayerNumber { get; set; } = 0;
        public string MatrixModelString { get; set; } = "";
        [Required]
        public List<int> MatrixModel { get; set; } = new();
        public string ChosenNumbers { get; set; } = "";
        public string CurrentLottery { get; set; } = "";
        public int CurrentHits { get; set; } = 0;
        public string CurrentWinningNumbers { get; set; } = "";
        public bool IsWinner { get; set; } = false;
    }
}

Models/ErrorViewModel.cs
namespace TrabajoFinal___Bingo_Web_MVC_Service.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BingoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TrabajoFinal___Bingo_Web_MVC_Service.Models;
using TrabajoFinal___Bingo_Web_MVC_Service.Services.Gambling;

namespace TrabajoFinal___Bingo_Web_MVC_Service.Controllers
{
    public class BingoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStartGamble _startGamble;
        private readonly IWager _wager;
        private readonly IEndGamble _endGamble;
        public BingoController(ILogger<HomeController> logger, IStartGamble startGamble, IWager wager, IEndGamble endGamble)
        {
            _logger = logger;
            _startGamble = startGamble;
            _wager = wager;
            _endGamble = endGamble;
        }

        public IActionResult FillBingos(int players) => View(_startGamble.CreateBingos(players));
        public IActionResult FillBingosFailed()
        {
            if (TempData.TryGetValue("InvalidModels", out var jsonModels) &&
                jsonModels is string jsonModelsString)
            {
                var models = JsonConvert.DeserializeObject<List<BingoViewModel>>(jsonModelsString);

                switch (TempData["FlawType"])
                {
                    case 492: ViewData["Missing"] = "CorrectRange";
                        ViewData["InvalidationMessage"] = "Must respet the range numbers order, the client-side hacking is forbidden, please cease to do it or we call the pertinent authorities."; break;
                    case 486: ViewData["Missing"] = "UniqueNumbers";
                        ViewData["InvalidationMessage"] = "There're repeated numbers, please do not choose same number, one unique per square cell"; break;
                }
                
                return View(models);
            }
            return RedirectToAction("FillBingos", (int)TempData["PlayersCount"]);
        }

        [HttpPost]
        public async Task<IActionResult> Shipping(List<BingoViewModel> models)
        {
            if (!ModelState.IsValid) { return RedirectToAction("FillBingos", models.Count); }
            else if (models == null || models.Count == 0) { return RedirectToAction("StartBingo", "Home"); }

            if (_startGamble.CheckUniqueNumbers(models))
            {
                if (_startGamble.VerifyCorrectRange(models))
                {
                    models = await _startGamble.SealNewBingos(models);
                    return View("BingoGambling", models);
                }
                else
                {
                    InputsFailure(models); TempData["FlawType"] = 492;
                    return RedirectToAction("FillBingosFailed");
                }
            }
            else
            {
                InputsFailure(models); TempData["FlawType"] = 486;
                return RedirectToAction("FillBingosFailed");
            }
        }
        private void InputsFailure(List<BingoViewModel> models)
        {
            var jsonModels = JsonConvert.SerializeObject(models);
            TempData["InvalidModels"] = jsonModels;
            TempData["PlayersCount"] = models.Count;
        }

        [HttpPost]
        public async Task<IActionResult> BingoGambling(int players) => View(await _endGamble.IsBingoEnd(_wager.GetNewDrawLot(_wager.RecoverBingoData(players))));
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TrabajoFinal___Bingo_Web_MVC_Service.Models;

namespace TrabajoFinal___Bingo_Web_MVC_Service.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index() => View();

        public IActionResult StartBingo() => View();

        public IActionResult AboutMe() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RecordController.cs
using Microsoft.AspNetCore.Mvc;
using TrabajoFinal___Bingo_Web_MVC_Service.Data.Entities;
using TrabajoFinal___Bingo_Web_MVC_Service.Data.Repository;
using TrabajoFinal___Bingo_Web_MVC_Service.Services.Extensions;

namespace TrabajoFinal___Bingo_Web_MVC_Service.Controllers
{
    public class RecordController : Controller
    {
        private readonly IRepository _repository;
        private readonly IDataModelExchange _dataModelExchange;
        public RecordController(IRepository repository, IDataModelExchange dataModelExchange)
        {
            _repository = repository;
            _dataModelExchange = dataModelExchange;
        }

        public IActionResult BingoWinners()
        {
            List<Bingo> winners = new();
            foreach (Bingo b in _repository.GetAllBingos())
            {
                if (b.IsWinner) { winners.Add(b); }
            }

            return View(_dataModelExchange.GetBingosModel(winners));
        }

        public IActionResult BingoList() => View(_dataModelExchange.GetBingosModel(_repository.GetAllBingos())); 

        public IActionResult BingoSet(int id) => View(_dataModelExchange.GetBingosModel(_dataModelExchange.GetBingoSet(id)));

        public IActionResult BingoDetail(int id) => View(_dataModelExchange.GetBingoModel(id));

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            await _repository.Delete(_dataModelExchange.GetBingoSet(id));

            return View("BingoList", _dataModelExchange.GetBingosModel(_repository.GetAllBingos()));
        }
    }
}

Views/Bingo/BingoGambling.cshtml
@model List<BingoViewModel>
@{
    bool there_is_a_winner = false;
    foreach (var model in Model) { if (model.IsWinner == true) { there_is_a_winner = true; break; } }

    BingoViewModel winner = new();
    BingoViewModel last = new();
    foreach (var model in Model) { if (model.IsWinner) { winner = model; break; } else { last = model; continue; } }
}

@if (there_is_a_winner)
{
    ViewData["Page Title"] = "Bingo Winner";
    ViewData["Page Carousel Title"] = "There's a winner!'";
    ViewData["Page Carousel Body First Paragraph"] = "The winner is the player number " + winner.PlayerNumber.ToString() + ":";
    ViewData["Page Carousel Body Second Paragraph"] = "";
    ViewData["Page Carousel Image"] = "/img/carousel-img/bingo_achieve_goal.jpeg";
    ViewData["Page Carousel ImageAlt"] = "Bingo Successful Goal";
    ViewData["Author Carousel Body First Paragraph"] = "And here is the winner block with the only model table structure presented that completed all the numbers within the lottery list.";
    ViewData["Author Carousel Body Second Paragraph"] = "";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img4.jpeg";
    ViewData["Author Carousel ImageAlt"] = "dusk";

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <h2>Bingo @winner.PlayerNumber Winner</h2>
        </div>
        <div class="col-4"></div>
    </div>

    <div class="row">
        <partial name="../Bingo/Partials/_BingoGamblePartial.cshtml" model="winner" />
    </div>

    <hr />

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <h3>Current Lottery</h3>
        </div>
        <div class="col-4"></div>
    </div>

    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 d-flex justify-content-center text-center" style="white-space: normal">
            <h3>@winner.CurrentLottery</h3>
        </div>
        <div class="col-1"></div>
    </div>
}
else
{
    ViewData["Page Title"] = "Bingo Gamble";
    ViewData["Page Carousel Title"] = "Bingo Gamble";
    ViewData["Page Carousel Body First Paragraph"] = "Now you must press the Lottery button for toss a number.";
    ViewData["Page Carousel Body Second Paragraph"] = "So then you will going to see the draw lottery until there is a winner. I mean, the first who complete his bingo.";
    ViewData["Page Carousel Image"] = "/img/carousel-img/bingo_draw_lottery.jpeg";
    ViewData["Page Carousel ImageAlt"] = "Bingo Gamble";
    ViewData["Author Carousel Body First Paragraph"] = "Here we got something more. The same model list table structure than before but with an extra case, this time mading with an if conditional in lieu of a switch case, wondering if the number square is matching with one in the lottery list.";
    ViewData["Author Carousel Body Second Paragraph"] = "In this case the matched number square is painted red in its background to mark up the match, waiting one of those models complete all of his numbers to declare a winner.";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img3.jpeg";
    ViewData["Author Carousel ImageAlt"] = "noon";
    Html.AntiForgeryToken();

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 text-center">
            <h2>Here below are the chosen Bingos:</h2>
        </div>
        <div class="col-3"></div>
    </div>

    @foreach (var model in Model)
    {
        <div class="row">
            <partial name="../Bingo/Partials/_BingoGamblePartial.cshtml" model="model" />
        </div>
        <hr />
    }
    @if (last.CurrentLottery != "")
    {
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <h3>Current Lottery</h3>
            </div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-1"></div>
            <div class="col d-flex justify-content-center text-center">
                <h3 style="white-space: normal">@last.CurrentLottery</h3>
            </div>
            <div class="col-1"></div>
        </div>
    }

    <div class="row">
        <div class="col-5"></div>
        <div class="col-2">
            <form asp-action="BingoGambling" method="post">
                <input type="hidden" name="players" value="@Model.Count" />
                <button type="submit" class="btn btn-danger text-center">Draw Lottery</button>
            </form>
        </div>
        <div class="col-5"></div>
    </div>
}

<script>LoadPlayerColors(); ConstructBsTable();</script>

Views/Bingo/FillBingos.cshtml
@model List<BingoViewModel>
@{
    ViewData["Page Title"] = "Start Bingo";
    ViewData["Page Carousel Title"] = "Bingo Settings";
    ViewData["Page Carousel Body First Paragraph"] = "First select the players number";
    ViewData["Page Carousel Body Second Paragraph"] = "Then each one must fill all the fields following the rule of each column range. First column allow numbers from 1 to 9, second allow from 10 to 19, third from 20 to 29, and so on up to last one, from 80 to 90.";
    ViewData["Page Carousel Image"] = "/img/carousel-img/bingo_complete.jpeg";
    ViewData["Page Carousel ImageAlt"] = "Bingo Gamble";
    ViewData["Author Carousel Body First Paragraph"] = "But here it begins to get interesting. I structure a Bootstrap table with the model list (through a partial view), where I iterate the list and each model spreads his numbers matrix within each td tag and selects the case with a switch.";
    ViewData["Author Carousel Body Second Paragraph"] = "The '-1' case is depicting an empty square and the '0' a filling one.";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img2.jpeg";
    ViewData["Author Carousel ImageAlt"] = "dawn";
}
@Html.AntiForgeryToken()

<div class="row">
    <div class="col-4"></div>
    <div class="col-4 text-center">
        <h1>Welcome to Bingo Web App Service</h1>
    </div>
    <div class="col-4"></div>
</div>

<div class="row">
    <div class="col-3"></div>
    <div class="col-6 text-center">
        <h4>Now each one must to choose a bingo color and fill in all the fields for their corresponding bingo.</h4>
    </div>
    <div class="col-3"></div>
</div>

<div class="row">
    <form class="form-control" asp-controller="Bingo" asp-action="Shipping" method="post">

        <partial name="../Bingo/Partials/_BuildBingoPartial.cshtml" model="@Model" />

        <div class="row">
            <div class="col-5"></div>
            <div class="col-2">
                <button type="submit" class="btn btn-primary text-center">Send Bingos and Play Lottery</button>
            </div>
            <div class="col-5"></div>
        </div>
    </form>
</div>

<script>LoadPlayerColors(); ConstructBsTable();</script>

Views/Bingo/FillBingosFailed.cshtml
@model List<BingoViewModel>
@{
    ViewData["Page Title"] = "Start Bingo";
    ViewData["Page Carousel Title"] = "Bingo Settings";
    ViewData["Page Carousel Body First Paragraph"] = "First select the players number";
    ViewData["Page Carousel Body Second Paragraph"] = "Then each one must fill all the fields following the rule of each column range. First column allow numbers from 1 to 9, second allow from 10 to 19, third from 20 to 29, and so on up to last one, from 80 to 90.";
    ViewData["Page Carousel Image"] = "/img/carousel-img/bingo_complete.jpeg";
    ViewData["Page Carousel ImageAlt"] = "Bingo Gamble";
    ViewData["Author Carousel Body First Paragraph"] = "Here I must create another page for the failed checking case, because the first page named 'FillBingos' creates a new model list and receive a int parameter with the players number, then it is sent to an action controller where it is valueted.";
    ViewData["Author Carousel Body Second Paragraph"] = "Like in this case the validation is failed then it returns here where besides not receiving any parameter, it interacts with TempData and deserialization of json objects to process the model list.";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img2.jpeg";
    ViewData["Author Carousel ImageAlt"] = "dawn";
}
@Html.AntiForgeryToken()

<div class="row">
    <div class="col-4"></div>
    <div class="col-4 text-center">
        <h1>Welcome to Bingo Web App Service</h1>
    </div>
    <div class="col-4"></div>
</div>

<div class="row">
    <div class="col-3"></div>
    <div class="col-6 text-center">
        <h4>Now each one must to choose a bingo color and fill in all the fields for their corresponding bingo.</h4>
    </div>
    <div class="col-3"></div>
</div>

<div class="alert alert-danger d-flex justify-content-center">@ViewData["InvalidationMessage"]</div>

<div class="row">
    <form class="form-control" asp-controller="Bingo" asp-action="Shipping" method="post">

        <partial name="../Bingo/Partials/_BuildBingoPartial.cshtml" model="@Model" />

        <div class="row">
            <div class="col-5"></div>
            <div class="col-2">
                <button type="submit" class="btn btn-primary text-center">Send Bingos and Play Lottery</button>
            </div>
            <div class="col-5"></div>
        </div>
    </form>
</div>

<script>LoadPlayerColors(); ConstructBsTable();</script>

Views/Home/Index.cshtml
@{
    ViewData["Page Title"] = "Home";
    ViewData["Page Carousel Title"] = "Welcome to the Luca E. Rodríguez Final Work for the Polo Tecnológico from Mina Clavero";
    ViewData["Page Carousel Body First Paragraph"] = "Please, read the following instructions to understand what's this page about.";
    ViewData["Page Carousel Body Second Paragraph"] = "";
    ViewData["Page Carousel Image"] = "/img/carousel-img/simbolic_casino.jpeg";
    ViewData["Page Carousel ImageAlt"] = "welcome to the casino";
    ViewData["Author Carousel Body First Paragraph"] = "I started this page writting some basic razor coding with some key links.";
    ViewData["Author Carousel Body Second Paragraph"] = "";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img1.jpeg";
    ViewData["Author Carousel ImageAlt"] = "begining";
}

<div class="text-center">
    <h2 class="display-4">Welcome to the Final Work for the institution called Polo Tecnológico from Mina Clavero, Argentina</h2>
    <p>For now it's just a Bingo App Service, but it is builded following the SOLID principles for made it scalable, so it is capable to 
        support new and multiple gambling apps services just changing a couple of line codes.</p>
    <p>So for begining with a Bingo party enter in the Bingo section <a asp-controller="Home" asp-action="StartBingo">clicking here</a>, 
        and select the number of participants, then each one must fill the his own bingo fields with a number following the set structure 
        of the same bingo.</p>
    <p>This is, a range of numbers allowed into each collumn, starting from 1 to 9, following from 10 to 19, and so on up to from 80 to 90.</p>
    <p>The bingo structure have 3 rows, and it have allowed from 1 to 2 fields inside each collumn, giving a random effect to it, where you could have 
        one or two fields of that specific range of possible numbers</p>
    <p>Once all the bingo fields have been set up, it's allowed to send that information directly to the database, and store it <a asp-controller="Record" asp-action="BingoList">there</a> to start the game's ranking.</p>
    <p>The first to win will be saved in the files and can be consulted in <a asp-controller="Record" asp-action="BingoWinners">our database record</a>.</p>
</div>

Views/Home/StartBingo.cshtml
@{
    ViewData["Page Title"] = "Start Bingo";
    ViewData["Page Carousel Title"] = "Bingo Settings";
    ViewData["Page Carousel Body First Paragraph"] = "First select the players number";
    ViewData["Page Carousel Body Second Paragraph"] = "Then each one must fill all the fields following the rule of each column range. First column allow numbers from 1 to 9, second allow from 10 to 19, third from 20 to 29, and so on up to last one, from 80 to 90.";
    ViewData["Page Carousel Image"] = "/img/carousel-img/bingo_complete.jpeg";
    ViewData["Page Carousel ImageAlt"] = "Bingo Gamble";
    ViewData["Author Carousel Body First Paragraph"] = "This is just a little of bootstrap for a simple form choosing number.";
    ViewData["Author Carousel Body Second Paragraph"] = "The number will be a parameter that set a list with models, all with the same structure to play the gamble.";
    ViewData["Author Carousel Image"] = "/img/carousel-img/author-img2.jpeg";
    ViewData["Author Carousel ImageAlt"] = "dawn";
}
<div class="row">
    <h1>Welcome to Bingo Web App Service</h1>
</div>

<div class="row">
    <div class="col">
        <h4>Please, choose the number of participants.</h4>
    </div>
</div>

<div class="row">
    <div class="col-3">
        <form class="form-control" asp-controller="Bingo" asp-action="FillBingos" method="post">
            <div class="row">
                <div class="col-8">
                    <label for="players" class="form-label">Number of players (max. 6)</label>
                </div>
                <div class="col-4">
                    <input id="players" name="players" class="form-control" type="number" max="6" min="1" />
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <button class="btn btn-outline-warning" type="submit">Choose number</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Record/BingoDetail.cshtml
@model BingoViewModel
@{
    ViewBag.RecordStage = "Single";
}

<div class="row">
    <h3>The chosen Bingo's details</h3>
</div>
<hr />
<div class="row">
    <form asp-controller="Record" asp-action="BingoSet" asp-route-id="@Model.Id">
        <div>
            <button type="submit" class="btn btn-primary m-2">Come Back</button>
        </div>
    </form>
</div>
<div class="row">
    <partial name="../Bingo/Partials/_BingoGamblePartial.cshtml" model="@Model" />
</div>
<div class="row">
    <form asp-controller="Record" asp-action="Remove" asp-route-id="@Model.Id">
        <div>
            <button type="submit" class="btn btn-danger m-2">Delete Record</button>
        </div>
    </form>
</div>

Views/Record/BingoSet.cshtml
@model List<BingoViewModel>
@{
    ViewBag.RecordStage = "Set";
}

<div class="row">
    <h3>The chosen Bingo's set</h3>
</div>
<hr />
<div class="row">
    <partial name="../Record/Partials/_BingoListPartial.cshtml" model="@Model" />
</div>
<div class="row">
    <form asp-controller="Record" asp-action="Remove" asp-route-id="@Model[0].Id">
        <div>
            <button type="submit" class="btn btn-danger m-2">Delete All Set</button>
        </div>
    </form>
</div>

Views/Record/Partials/_BingoListPartial.cshtml
@model List<BingoViewModel>
@{
}

<div class="container">
    <div class="table-responsive-lg">
        <table class="table table-bordered">
            <thead>
                <tr class="row">
                    <th class="col-2">Player Number</th>
                    <th class="col-3">Numbers</th>
                    <th class="col-3">Loterry</th>
                    <th class="col-2">Winning Numbers</th>
                    <th class="col-2">Options</th>
                </tr>
            </thead>
            <tbody>
                @for (int r = 0; r < Model.Count; r++)
                {
                    <tr class="row" style="white-space: normal">
                        <td class="col-2">@Model[r].PlayerNumber</td>
                        <td class="col-3">@Model[r].ChosenNumbers</td>
                        <td class="col-3">@Model[r].CurrentLottery</td>
                        <td class="col-2">
                            Hits: @Model[r].CurrentHits
                            @Model[r].CurrentWinningNumbers
                        </td>
                        <td class="col-2">
                            @switch (ViewBag.RecordStage)
                            {
                                case "All":
                                    <form asp-controller="Record" asp-action="BingoSet" asp-route-id="@Model[r].Id">
                                        <div>
                                            <button type="submit" class="btn btn-primary m-2">See Bingo's set</button>
                                        </div>
                                    </form>
                                    <form asp-controller="Record" asp-action="BingoDetail" asp-route-id="@Model[r].Id">
                                        <div>
                                            <button type="submit" class="btn btn-info m-2">See Bingo detail</button>
                                        </div>
                                    </form>
                                    <form asp-controller="Record" asp-action="Remove" asp-route-id="@Model[r].Id">
                                        <div>
                                            <button type="submit" class="btn btn-danger m-2">Delete Record</button>
                                        </div>
                                    </form>
                                ;break;

                                case "Set":
                                    <form asp-controller="Record" asp-action="BingoDetail" asp-route-id="@Model[r].Id">
                                        <div>
                                            <button type="submit" class="btn btn-info m-2">See Bingo detail</button>
                                        </div>
                                    </form>
                                ;break;
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Page Title"] - Bingo Web Service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header class="mb-5">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-black order-bottom box-shadow fixed-top">
            <div class="container-xl">
                <a class="navbar-brand text-warning" asp-controller="Home" asp-action="Index">Bingo Web App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-arround">
                    <ul class="navbar-nav flex-grow-1 text-warning">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="AboutMe">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="StartBingo">Start Bingo Now</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Record" asp-action="BingoList">See All Bingo Record List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Record" asp-action="BingoWinners">See Bingo Winners List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <div id="pageCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#pageCarousel" data-bs-slide-to="0" class="active" aria-current="true"></button>
                        <button type="button" data-bs-target="#pageCarousel" data-bs-slide-to="1"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active" data-bs-interval="10000" style="min-height: 10rem; max-height: 25rem;">
                            <img class="d-block w-100 img-fluid" src="@ViewData["Page Carousel Image"]" alt="@ViewData["Page Carousel ImageAlt"]" style="opacity: 0.5;" />
                            <div class="carousel-caption d-none d-md-block text-dark">
                                <h3>@ViewData["Page Carousel Title"]</h3>
                                <p>@ViewData["Page Carousel Body First Paragraph"]</p>
                                <p>@ViewData["Page Carousel Body Second Paragraph"]</p>
                            </div>
                        </div>
                        <div class="carousel-item" data-bs-interval="4000" style="min-height: 10rem; max-height: 25rem;">
                            <img class="d-block w-100 img-fluid" src="@ViewData["Author Carousel Image"]" alt="@ViewData["Author Carousel ImageAlt"]" style="opacity: 0.5;" />
                            <div class="carousel-caption d-none d-md-block text-dark">
                                <h3>About the build-in programming logic over this specific page...</h3>
                                <p>@ViewData["Author Carousel Body First Paragraph"]</p>
                                <p>@ViewData["Author Carousel Body Second Paragraph"]</p>
                                <p>To know more about this web-app author <a asp-controller="Home" asp-action="AboutMe">click here</a>.</p>
                            </div>
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#pageCarousel" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#pageCarousel" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
        </div>
        <main role="main" class="mt-2 pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - This is a project based in my successful final work for my course in the Polo Tecnológico from Mina Clavero - For more info click in <a asp-controller="Home" asp-action="About Me">About Me</a> Section
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>